export const mapType = [
  { key: "assault", name: "점령" },
  { key: "clash", name: "격돌" },
  { key: "control", name: "쟁탈" },
  { key: "escort", name: "호위" },
  { key: "flashpoint", name: "플래시포인트" },
  { key: "hybrid", name: "혼합" },
  { key: "push", name: "밀기" },
];

export const mapName = {
  aatlis: "아틀리스",
  "antarctic-peninsula": "남극 반도",
  anubis: "아누비스 신전",
  "arena-victoriae": "아레나 빅토리아",
  ayutthaya: "아유타야",
  "black-forest": "검은 숲",
  "blizzard-world": "블리자드 월드",
  busan: "부산",
  castillo: "카스티요",
  "chateau-guillard": "샤토 기야르",
  "circuit-royal": "서킷 로얄",
  colosseo: "콜로세오",
  dorado: "도라도",
  "ecopoint-antarctica": "에코포인트: 남극",
  eichenwalde: "아이헨발데",
  esperanca: "에스페란사",
  gogadoro: "고가도로",
  hanamura: "하나무라",
  hanaoka: "하나오카",
  havana: "하바나",
  hollywood: "할리우드",
  horizon: "호라이즌 달 기지",
  ilios: "일리오스",
  junkertown: "쓰레기촌",
  "lijiang-tower": "리장 타워",
  kanezaka: "카네자카",
  "kings-row": "왕의 길",
  malevento: "말레벤토",
  midtown: "미드타운",
  necropolis: "네크로폴리스",
  nepal: "네팔",
  "neon-junction": "네온 정션",
  "new-junk-city": "뉴 정크 시티",
  "new-queen-street": "뉴 퀸 스트리트",
  numbani: "눔바니",
  oasis: "오아시스",
  paraiso: "파라이수",
  paris: "파리",
  petra: "페트라",
  "place-lacroix": "플라스 라크루아",
  "powder-keg-mine": "파우더 케그 광산",
  "practice-range": "연습 전투장",
  "redwood-dam": "레드우드 댐",
  rialto: "리알토",
  "route-66": "66번 국도",
  runasapi: "루나사피",
  samoa: "사모아",
  "shambali-monastery": "샴발리 수도원",
  suravasa: "수라바사",
  "thames-district": "템스 지구",
  "throne-of-anubis": "아누비스 왕좌",
  volskaya: "볼스카야 인더스트리",
  "watchpoint-gibraltar": "감시 기지: 지브롤터",
  "workshop-chamber": "워크샵 챔버",
  "workshop-expanse": "워크샵 익스팬스",
  "workshop-green-screen": "워크샵 그린 스크린",
  "workshop-island": "워크샵 섬",
  "wuxing-university": "우싱 대학교",
};
